fixed syntax error

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,13 +26,13 @@ runs:
     - name: Clone repository
       shell: bash
       run: |
-        REPOSITORY_DIRNAME=$(echo "${{ inputs.repository }}" | sed -e 's%/%-%g'
+        REPOSITORY_DIRNAME=$(echo "${{ inputs.repository }}" | sed -e 's%/%-%g')
         git clone "git@github.com:${{ inputs.repository }}" "/github/workspace/${REPOSITORY_DIRNAME}"
     - name: Create upstream branch
       shell: bash
       run: |
         REPOSITORY_DIRNAME=$(echo "${{ inputs.repository }}" | sed -e 's%/%-%g')
-        cd "/github/workspace/${REPOSITORY_DIRNAME}"
+        cd "/github/workspace/${REPOSITORY_DIRNAME}" || { echo "Could not change to directory. Exiting." && exit 254; }
         UPSTREAM_BRANCH_PREFIX="${{ inputs.branch-prefix }}"
         TRIGGERING_VERSION="${{ inputs.triggering-version }}"
         git checkout -b "${UPSTREAM_BRANCH_PREFIX}/test-${TRIGGERING_VERSION}"
@@ -40,14 +40,14 @@ runs:
       shell: bash
       run: |
         REPOSITORY_DIRNAME=$(echo "${{ inputs.repository }}" | sed -e 's%/%-%g')
-        cd "/github/workspace/${REPOSITORY_DIRNAME}"
+        cd "/github/workspace/${REPOSITORY_DIRNAME}" ||  { echo "Could not change to directory. Exiting." && exit 254; }
         TRIGGERING_VERSION="${{ inputs.triggering-version }}"
         sed -i -e "s/^DOCKER_BASE_IMAGE_VER=.*$/DOCKER_BASE_IMAGE_VER=${TRIGGERING_VERSION}/g" .config
     - name: Commit updated config to dependent repository
       shell: bash
       run: |
         REPOSITORY_DIRNAME=$(echo "${{ inputs.repository }}" | sed -e 's%/%-%g')
-        cd "/github/workspace/${REPOSITORY_DIRNAME}"
+        cd "/github/workspace/${REPOSITORY_DIRNAME}" || { echo "Could not change to directory. Exiting." && exit 254; }
         git add .config
         case "${{ inputs.change-type }}" in
           patch)
